CREATE TABLE ALUNO(
rm NUMBER(5) NOT NULL,
nm_aluno VARCHAR2(30) NOT NULL,
rg NUMBER(9) NOT NULL,
dt_niver DATE
);

ALTER TABLE ALUNO
  ADD CONSTRAINT ALUNO_PK PRIMARY KEY (rm);
  
INSERT INTO ALUNO (rm,nm_aluno,rg,dt_niver)
  VALUES (69807,'Mateus',123456789,NULL);
  
INSERT INTO ALUNO (rm,nm_aluno,rg)
  VALUES (89807,'Mateus',123456789);
  
COMMIT;

SELECT * FROM ALUNO;

UPDATE ALUNO
  SET nm_aluno = 'ANDRE'
WHERE rm = 89807

COMMIT;

DELETE FROM ALUNO
  WHERE rm = 69807;

COMMIT;

DROP TABLE ALUNO;
