ALTER SESSION SET NLS_LANGUAGE='BRAZILIAN PORTUGUESE';
ALTER SESSION SET NLS_TERRITORY=BRAZIL;

---------------------------
-- CRIAÇÃO DE SEQUENCES
---------------------------

DROP SEQUENCE DEPARTMENTS_SEQ;
DROP SEQUENCE EMPLOYEES_SEQ;
DROP SEQUENCE LOCATIONS_SEQ;


CREATE SEQUENCE  "DEPARTMENTS_SEQ"  MINVALUE 1 MAXVALUE 9990 INCREMENT BY 10 START WITH 280 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "EMPLOYEES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 207 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "LOCATIONS_SEQ"  MINVALUE 1 MAXVALUE 9900 INCREMENT BY 100 START WITH 3300 NOCACHE  NOORDER  NOCYCLE ;



---------------------------
-- CRIAÇÃO DE TABELAS
---------------------------

DROP TABLE COUNTRIES CASCADE CONSTRAINTS;
DROP TABLE REGIONS CASCADE CONSTRAINTS;
DROP TABLE LOCATIONS CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS;
DROP TABLE JOBS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;
DROP TABLE JOB_HISTORY CASCADE CONSTRAINTS;


CREATE TABLE COUNTRIES
(
	COUNTRY_ID  CHAR(2 BYTE)   CONSTRAINT  COUNTRY_ID_NN NOT NULL ,
	COUNTRY_NAME  VARCHAR2(40 BYTE)  NULL ,
	REGION_ID  NUMBER  NULL ,
CONSTRAINT  COUNTRY_C_ID_PK PRIMARY KEY (COUNTRY_ID)
);


CREATE TABLE DEPARTMENTS
(
	DEPARTMENT_ID  NUMBER(4)  NOT NULL ,
	DEPARTMENT_NAME  VARCHAR2(30 BYTE)   CONSTRAINT  DEPT_NAME_NN NOT NULL ,
	MANAGER_ID  NUMBER(6)  NULL ,
	LOCATION_ID  NUMBER(4)  NULL 
);

ALTER TABLE DEPARTMENTS
	ADD CONSTRAINT  DEPT_ID_PK PRIMARY KEY (DEPARTMENT_ID);


CREATE TABLE EMPLOYEES
(
	EMPLOYEE_ID  NUMBER(6)  NOT NULL ,
	FIRST_NAME  VARCHAR2(20 BYTE)  NULL ,
	LAST_NAME  VARCHAR2(25 BYTE)   CONSTRAINT  EMP_LAST_NAME_NN NOT NULL ,
	EMAIL  VARCHAR2(25 BYTE)   CONSTRAINT  EMP_EMAIL_NN NOT NULL ,
	PHONE_NUMBER  VARCHAR2(20 BYTE)  NULL ,
	HIRE_DATE  DATE   CONSTRAINT  EMP_HIRE_DATE_NN NOT NULL ,
	JOB_ID  VARCHAR2(10 BYTE)   CONSTRAINT  EMP_JOB_NN NOT NULL ,
	SALARY  NUMBER(8,2)  NULL  CONSTRAINT  EMP_SALARY_MIN CHECK (salary > 0),
	COMMISSION_PCT  NUMBER(2,2)  NULL ,
	MANAGER_ID  NUMBER(6)  NULL ,
	DEPARTMENT_ID  NUMBER(4)  NULL 
);

ALTER TABLE EMPLOYEES
	ADD CONSTRAINT  EMP_EMP_ID_PK PRIMARY KEY (EMPLOYEE_ID);

ALTER TABLE EMPLOYEES
	ADD CONSTRAINT  EMP_EMAIL_UK UNIQUE (EMAIL);

CREATE INDEX EMP_NAME_IX ON EMPLOYEES
(
	LAST_NAME  ASC,
	FIRST_NAME  ASC
);



CREATE TABLE JOB_HISTORY
(
	EMPLOYEE_ID  NUMBER(6)   CONSTRAINT  JHIST_EMPLOYEE_NN NOT NULL ,
	START_DATE  DATE   CONSTRAINT  JHIST_START_DATE_NN NOT NULL ,
	END_DATE  DATE   CONSTRAINT  JHIST_END_DATE_NN NOT NULL ,
	JOB_ID  VARCHAR2(10 BYTE)   CONSTRAINT  JHIST_JOB_NN NOT NULL ,
	DEPARTMENT_ID  NUMBER(4)  NULL ,
CONSTRAINT  JHIST_DATE_INTERVAL CHECK  (end_date > start_date)
);

ALTER TABLE JOB_HISTORY
	ADD CONSTRAINT  JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY (EMPLOYEE_ID,START_DATE);


CREATE TABLE JOBS
(
	JOB_ID  VARCHAR2(10 BYTE)  NOT NULL ,
	JOB_TITLE  VARCHAR2(35 BYTE)   CONSTRAINT  JOB_TITLE_NN NOT NULL ,
	MIN_SALARY  NUMBER(6)  NULL ,
	MAX_SALARY  NUMBER(6)  NULL 
);


ALTER TABLE JOBS
	ADD CONSTRAINT  JOB_ID_PK PRIMARY KEY (JOB_ID);



CREATE TABLE LOCATIONS
(
	LOCATION_ID  NUMBER(4)  NOT NULL ,
	STREET_ADDRESS  VARCHAR2(40 BYTE)  NULL ,
	POSTAL_CODE  VARCHAR2(12 BYTE)  NULL ,
	CITY  VARCHAR2(30 BYTE)   CONSTRAINT  LOC_CITY_NN NOT NULL ,
	STATE_PROVINCE  VARCHAR2(25 BYTE)  NULL ,
	COUNTRY_ID  CHAR(2 BYTE)  NULL 
);

ALTER TABLE LOCATIONS
	ADD CONSTRAINT  LOC_ID_PK PRIMARY KEY (LOCATION_ID);


CREATE INDEX LOC_CITY_IX ON LOCATIONS
(
	CITY  ASC
);


CREATE INDEX LOC_STATE_PROVINCE_IX ON LOCATIONS
(
	STATE_PROVINCE  ASC
);


CREATE TABLE REGIONS
(
	REGION_ID  NUMBER   CONSTRAINT  REGION_ID_NN NOT NULL ,
	REGION_NAME  VARCHAR2(25 BYTE)  NULL 
);


ALTER TABLE REGIONS
	ADD CONSTRAINT  REG_ID_PK PRIMARY KEY (REGION_ID);


----------------------------------------
-- CRIANDO FOREING KEYs (FK)
-----------------------------------------


ALTER TABLE COUNTRIES
	ADD (CONSTRAINT  COUNTR_REG_FK FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID));


ALTER TABLE DEPARTMENTS
	ADD (CONSTRAINT  DEPT_LOC_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID));


ALTER TABLE DEPARTMENTS
	ADD (CONSTRAINT  DEPT_MGR_FK FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID));


ALTER TABLE EMPLOYEES
	ADD (CONSTRAINT  EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID));


ALTER TABLE EMPLOYEES
	ADD (CONSTRAINT  EMP_JOB_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID));


ALTER TABLE EMPLOYEES
	ADD (CONSTRAINT  EMP_MANAGER_FK FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID));


ALTER TABLE JOB_HISTORY
	ADD (CONSTRAINT  JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID));


ALTER TABLE JOB_HISTORY
	ADD (CONSTRAINT  JHIST_EMP_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID));


ALTER TABLE JOB_HISTORY
	ADD (CONSTRAINT  JHIST_JOB_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID));


ALTER TABLE LOCATIONS
	ADD (CONSTRAINT  LOC_C_ID_FK FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID));


