CREATE TABLE GRAVADORA (
cod_gravadora NUMBER(5) NOT NULL,
nm_razao_social VARCHAR2(100) NOT NULL,
nr_cnpj NUMBER(11) NOT NULL,
ds_endereco VARCHAR2(200) NOT NULL,
nr_telefone NUMBER(11) NOT NULL,
ds_email VARCHAR2(80) ,
ds_url VARCHAR2(90),
nm_contato VARCHAR2(80) NOT NULL
);

CREATE TABLE CD (
cd_cd NUMBER(5) NOT NULL,
nm_titulo VARCHAR2(100) NOT NULL,
dt_lancamento DATE NOT NULL,
vl_preco_venda NUMBER(3,2) NOT NULL,
ds_faixa VARCHAR2(100)
);

CREATE TABLE CD_MUSICA(
cd_cd NUMBER(5) NOT NULL,
cd_musica NUMBER(5) NOT NULL
);

CREATE TABLE MUSICA(
cd_musica NUMBER(5) NOT NULL,
nm_musica VARCHAR2(80) NOT NULL,
vl_duracao NUMBER(3,2) NOT NULL,
dt_composicao DATE
);

CREATE TABLE MUSICA_AUTOR(
cd_musica NUMBER(5) NOT NULL,
cd_autor NUMBER(4) NOT NULL
);

CREATE TABLE AUTOR(
cd_autor NUMBER(4) NOT NULL,
nm_autor VARCHAR2(80) NOT NULL
);

CREATE TABLE FAIXA_PRECO (
cd_faixa_preco NUMBER(4) NOT NULL,
ds_faixa_preco VARCHAR2(100) NOT NULL,
vl_inicial NUMBER(3,2) NOT NULL,
vl_final NUMBER(3,2) NOT NULL
);


--PRIMARY KEYS
ALTER TABLE  GRAVADORA
  ADD CONSTRAINT GRAVADORA_PK PRIMARY KEY (cod_gravadora);
  
ALTER TABLE CD
  ADD CONSTRAINT CD_PK PRIMARY KEY (cd_cd);
  
ALTER TABLE CD_MUSICA 
  ADD CONSTRAINT CD_CD_MUSICA PRIMARY KEY (cd_cd,cd_musica);

ALTER TABLE MUSICA
  ADD CONSTRAINT MUSICA_PK PRIMARY KEY (cd_musica);
  
ALTER TABLE AUTOR
  ADD CONSTRAINT AUTOR_PK PRIMARY KEY (cd_autor);
  
  ALTER TABLE MUSICA_AUTOR
    ADD CONSTRAINT MUSICA_AUTOR_PK PRIMARY KEY (cd_musica,cd_autor);
  
ALTER TABLE FAIXA_PRECO
  ADD CONSTRAINT FAIXA_PRECO_PK PRIMARY KEY (cd_faixa_preco);

--FOREIGN KEYS
ALTER TABLE CD ADD cod_gravadora NUMBER(5);
ALTER TABLE CD ADD cd_musica NUMBER(5);

ALTER TABLE CD
  ADD(FOREIGN KEY (cod_gravadora)
      REFERENCES GRAVADORA(cod_gravadora));

ALTER TABLE CD
  ADD(FOREIGN KEY (cd_musica)
      REFERENCES MUSICA(cd_musica));

ALTER TABLE MUSICA ADD cd_autor NUMBER(4);

ALTER TABLE MUSICA
  ADD(FOREIGN KEY (cd_autor)
      REFERENCES AUTOR(cd_autor));
      
ALTER TABLE CD_MUSICA
  ADD(FOREIGN KEY (cd_cd)
      REFERENCES CD(cd_cd));

ALTER TABLE CD_MUSICA
  ADD(FOREIGN KEY (cd_musica)
      REFERENCES MUSICA(cd_musica));
      
ALTER TABLE MUSICA_AUTOR
  ADD (FOREIGN KEY (cd_musica)
      REFERENCES MUSICA(cd_musica));

ALTER TABLE MUSICA_AUTOR
  ADD (FOREIGN KEY (cd_autor)
      REFERENCES AUTOR(cd_autor));
      
--DROP TABLE
DROP TABLE CD_MUSICA;
DROP TABLE MUSICA_AUTOR;
DROP TABLE CD;
DROP TABLE MUSICA;
DROP TABLE AUTOR;
DROP TABLE FAIXA_PRECO;
DROP TABLE GRAVADORA;

