/*----------------------------------------------------------------------------------------------*/
/*                              REVISÃO PARA PROVA SEMESTRAL 2SEM                               */
/*OBJETIVO: CRIACAO DE TABELAS , CHAVES PRIMRIAS E ESTRANGEIRAS, INSERÇÃO DE DADOS E CONSULTAS  */
/*AUTOR: MATEUS INGEGNERI ATTIE                                                                 */
/*DATA DA CRIA��O: 25/09/2014                                                                   */
/*----------------------------------------------------------------------------------------------*/
ALTER SESSION SET NLS_TERRITORY = BRAZIL;
ALTER SESSION SET NLS_LANGUAGE = 'BRAZILIAN PORTUGUESE';

CREATE TABLE FUNCIONARIO(
FUNC_ID NUMBER(3) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
SOBRENOME VARCHAR2(50) NOT NULL,
CARGO_ID NUMBER(2) NOT NULL,
DEPTO_ID NUMBER(2) NOT NULL,
SALARIO NUMBER(6,2)
);


ALTER TABLE FUNCIONARIO
  ADD CONSTRAINT FUNCIONARIO_PK PRIMARY KEY(FUNC_ID);

CREATE TABLE DEPARTAMENTO( 
DEPTO_ID NUMBER(2),
DEPTO_NOME VARCHAR2(100),
DEPTO_GERENTE VARCHAR2(100)
);

ALTER TABLE DEPARTAMENTO
  ADD CONSTRAINT DEPTO_PK PRIMARY KEY(DEPTO_ID);
  
CREATE TABLE CARGO(
CARGO_ID NUMBER(2) NOT NULL,
CARGO_NOME VARCHAR(100) NOT NULL
);
  
ALTER TABLE CARGO
  ADD CONSTRAINT CARGO_PK PRIMARY KEY(CARGO_ID);
  
  
--FOREIGNS KEYS

ALTER TABLE FUNCIONARIO
ADD(FOREIGN KEY(CARGO_ID)
    REFERENCES CARGO(CARGO_ID));
    

ALTER TABLE FUNCIONARIO
ADD(FOREIGN KEY(DEPTO_ID)
    REFERENCES DEPARTAMENTO(DEPTO_ID));

    
--SEQUENCE

CREATE SEQUENCE SEQ_CODIGO_FUNC INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 999 NOCACHE NOCYCLE;
    
--INSERINDO VALORES

INSERT INTO CARGO(CARGO_ID,CARGO_NOME)
  VALUES(1,'MANOBRISTA');
INSERT INTO CARGO(CARGO_ID,CARGO_NOME)
  VALUES(2,'ADMINISTRADOR');
INSERT INTO CARGO(CARGO_ID,CARGO_NOME)
  VALUES(3,'GERENTE');
INSERT INTO CARGO(CARGO_ID,CARGO_NOME)
  VALUES(4,'SOCIO');
  
INSERT INTO FUNCIONARIO(FUNC_ID,NOME,SOBRENOME,CARGO_ID,DEPTO_ID)
  VALUES(SEQ_CODIGO_FUNC.NEXTVAL,'MIGUEL','ATTIE',4,2);
INSERT INTO FUNCIONARIO(FUNC_ID,NOME,SOBRENOME,CARGO_ID,DEPTO_ID)
  VALUES(SEQ_CODIGO_FUNC.NEXTVAL,'MATEUS','ATTIE',2,2);
INSERT INTO FUNCIONARIO(FUNC_ID,NOME,SOBRENOME,CARGO_ID,DEPTO_ID)
  VALUES(SEQ_CODIGO_FUNC.NEXTVAL,'MUNIR','MITRE',4,1);
INSERT INTO FUNCIONARIO(FUNC_ID,NOME,SOBRENOME,CARGO_ID,DEPTO_ID)
  VALUES(SEQ_CODIGO_FUNC.NEXTVAL,'SAMIR','MITRE',3,1);
INSERT INTO FUNCIONARIO(FUNC_ID,NOME,SOBRENOME,CARGO_ID,DEPTO_ID)
  VALUES(SEQ_CODIGO_FUNC.NEXTVAL,'MARIO','RIBEIRO',1,1);
INSERT INTO FUNCIONARIO(FUNC_ID,NOME,SOBRENOME,CARGO_ID,DEPTO_ID)
  VALUES(SEQ_CODIGO_FUNC.NEXTVAL,'SERGIO','SILVA',1,1);


INSERT INTO DEPARTAMENTO(DEPTO_ID,DEPTO_NOME,DEPTO_GERENTE)
  VALUES(1,'CANTAREIRA','MUNIR');
INSERT INTO DEPARTAMENTO(DEPTO_ID,DEPTO_NOME,DEPTO_GERENTE)
  VALUES(2,'STO EGIDIO','MIGUEL');

UPDATE DEPARTAMENTO SET DEPTO_NOME = 'CANTAREIRA(ESTACIONAMENTO)'
WHERE DEPTO_ID = 1;
UPDATE DEPARTAMENTO SET DEPTO_NOME = 'STO EGIDIO(ADMINISTRAÇÃO)'
WHERE DEPTO_ID = 2;

UPDATE FUNCIONARIO SET SALARIO =1100
WHERE NOME = 'MATEUS';
UPDATE FUNCIONARIO SET SALARIO =3300
WHERE NOME = 'SAMIR';
UPDATE FUNCIONARIO SET SALARIO =1200
WHERE CARGO_ID = 1;
UPDATE FUNCIONARIO SET SALARIO =7000
WHERE CARGO_ID = 4;

COMMIT;

--QUERYS ALEATORIAS 

DESC FUNCIONARIO;
DESC CARGO;
DESC DEPARTAMENTO;

SELECT * FROM FUNCIONARIO;
SELECT * FROM CARGO;
SELECT * FROM DEPARTAMENTO;

SELECT FUNC_ID AS "ID", NOME ||' '|| SOBRENOME AS "NOME COMPLETO",DEPTO_ID AS DEPARTAMENTO FROM FUNCIONARIO;

SELECT FUNC_ID,CARGO_ID,NOME,SOBRENOME FROM FUNCIONARIO
WHERE NOME LIKE '_A%';

SELECT FUNC_ID ||', '|| NOME||' '||SOBRENOME||', '|| SALARIO AS "SALARIO > 3000" FROM FUNCIONARIO
WHERE SALARIO > 3000;

SELECT FUNC_ID AS "ID",NOME||' '||SOBRENOME AS "NOME COMPLETO",TO_CHAR(SALARIO,'L9999.99') AS SALARIO FROM FUNCIONARIO
WHERE SALARIO BETWEEN 1000 AND 2000
ORDER BY SALARIO ASC;

SELECT FUNC_ID,NOME||' '||SOBRENOME AS "NOME COMPLETO" FROM FUNCIONARIO
WHERE CARGO_ID = &CARGO_ID;

SELECT INITCAP(NOME)||' '||INITCAP(SOBRENOME) FROM FUNCIONARIO;

SELECT F.NOME , F.SOBRENOME,F.CARGO_ID,F.SALARIO,D.DEPTO_ID,D.DEPTO_NOME,D.DEPTO_GERENTE 
FROM FUNCIONARIO F,DEPARTAMENTO D
WHERE F.DEPTO_ID = D.DEPTO_ID
ORDER BY F.NOME;

SELECT NOME||', '||
  CASE
  WHEN DEPTO_ID = 1 THEN 'ESTACIONAMENTO'
  WHEN DEPTO_ID = 2 THEN 'ADMINISTRAÇÃO'
  ELSE 'NO DEPARTMENT'
  END
  AS "NOMES E DEPTOS"
FROM FUNCIONARIO;

SELECT NOME,CARGO_ID,DECODE(CARGO_ID,1,'MANOBRISTA',2,'ADM',3,'GERENTE',4,'SOCIO','NULL')AS CARGO FROM FUNCIONARIO;

SELECT MAX(SALARIO) AS "SALARIO MAXIMO" , MIN(SALARIO) AS "SALARIO MINIMO",
        SUM(SALARIO) AS "SOMA TOTAL" , CAST(AVG(SALARIO)AS NUMBER(8,2)) AS MÉDIA FROM FUNCIONARIO;

SELECT CARGO_ID,COUNT(FUNC_ID) AS "FUNCIONARIOS COM O MESMO CARGO" FROM FUNCIONARIO
WHERE CARGO_ID IS NOT NULL
GROUP BY CARGO_ID
ORDER BY CARGO_ID;

SELECT DISTINCT F.SOBRENOME AS SOBRENOME,F.DEPTO_ID AS DEPTO,FE.NOME AS "FUNC NO MESMO DEPTO"
FROM FUNCIONARIO F, FUNCIONARIO FE
WHERE F.DEPTO_ID = FE.DEPTO_ID
AND F.SOBRENOME = 'MITRE'
ORDER BY FE.NOME;

SELECT F.NOME,F.SOBRENOME,D.DEPTO_ID,D.DEPTO_NOME
FROM FUNCIONARIO F , DEPARTAMENTO D
WHERE F.DEPTO_ID = D.DEPTO_ID AND F.SALARIO > 2000
ORDER BY D.DEPTO_NOME;



  

















