--1
SELECT last_name,JOB_ID,SALARY AS SAL
  FROM EMPLOYEES;
--2  
SELECT * FROM JOB_GRADES;

DESC EMPLOYEES
--3
--X NAO � OPERADOR ARITMETICO
--"ANNUAL SALARY"
--SAL NAO � UMA VARIAVEL
--FALTA A VIRGULA DEPOIS DE LAST_NAME
SELECT EMPLOYEE_ID,LAST_NAME
      SAL X 12 ANNUAL SALARY
FROM EMPLOYEES;

--4  
SELECT  LAST_NAME ||', ' || JOB_ID AS "EMPLOYEE AND TITLE"
FROM EMPLOYEES; 

--5 ???
SELECT EMPLOYEE_ID || ', ' ||
FIRST_NAME ||', ' || 
LAST_NAME ||', ' ||
EMAIL ||', ' ||
PHONE_NUMBER ||', ' ||
HIRE_DATE ||', ' ||
JOB_ID ||', ' ||
SALARY ||', ' ||
COMMISSION_PCT ||', ' ||
MANAGER_ID||', ' || 
DEPARTMENT_ID 
AS THE_OUTPUT
FROM EMPLOYEES;

--6
SELECT LAST_NAME,JOB_ID,SALARY FROM EMPLOYEES
  WHERE JOB_ID LIKE 'ST_MAN' OR JOB_ID LIKE 'SA_REP' AND  SALARY != 2500 AND SALARY != 3500 AND SALARY!= 7000;
  
--7  
SELECT LAST_NAME ||' RECEBE ' ||SALARY  ||' MENSALMENTE ,MAS DESEJA RECEBER ' ||SALARY*3 AS "DREAM SALARIES"
FROM EMPLOYEES;

--8
SELECT COUNT(*) AS "PESSOAS COM O CARGO ST_CLERK" FROM EMPLOYEES
WHERE JOB_ID LIKE '%ST_CLERK%';

--OU
SELECT COUNT(EMPLOYEE_ID) AS "FUNCIONARIOS COM O MESMO CARGO",JOB_ID FROM EMPLOYEES
WHERE JOB_ID = '&JOB_ID'
GROUP BY JOB_ID;

--9
SELECT COUNT(*) "TOTAL FUNCIONARIOS" FROM EMPLOYEES;
SELECT COUNT(*) AS "FUNCIONARIOS ENTRE 1995 E 1998" FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN TO_DATE('01/01/1995','DD/MM/YYYY') AND TO_DATE('31/12/1998','DD/MM/YYYY');
