CREATE TABLE XBC(
CODIGO NUMBER(2),
NOME VARCHAR2(30)
);

ALTER TABLE XBC ADD CONSTRAINT CODIGO_PK PRIMARY KEY (CODIGO);

DESC XBC

--CRIANDO A SEQUENCE
CREATE SEQUENCE SEQ_CODIGO_XBC INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCACHE NOCYCLE;


--ALTERANDO A SEQUENCE
ALTER SEQUENCE SEQ_CODIGO_XBC INCREMENT BY 1 MAXVALUE 9 NOCACHE NOCYCLE;


--INSERCAO COM A PRIMEIRA SEQUENCE ANTES DO ALTER
INSERT INTO XBC(CODIGO,NOME)
  VALUES(SEQ_CODIGO_XBC.NEXTVAL,'MATEUS');


INSERT INTO XBC(CODIGO,NOME)
  VALUES(SEQ_CODIGO_XBC.NEXTVAL,'RAFAEL');

INSERT INTO XBC(CODIGO,NOME)
  VALUES(SEQ_CODIGO_XBC.NEXTVAL,'ANDRÉ');

COMMIT;

SELECT * FROM XBC;

DELETE XBC WHERE CODIGO = 2;

--INSERÇÃO APOS O DELETE
INSERT INTO XBC(CODIGO,NOME)
  VALUES(SEQ_CODIGO_XBC.NEXTVAL,'MATHEUS');

--INSERÇÃO APOS O ALTER SEQUENCE
INSERT INTO XBC(CODIGO,NOME)
  VALUES(SEQ_CODIGO_XBC.NEXTVAL,'BRUNETSWKI');
INSERT INTO XBC(CODIGO,NOME)
  VALUES(SEQ_CODIGO_XBC.NEXTVAL,'JACKSON TELLER');
INSERT INTO XBC(CODIGO,NOME)
  VALUES(SEQ_CODIGO_XBC.NEXTVAL,'JUICE');
INSERT INTO XBC(CODIGO,NOME)
  VALUES(SEQ_CODIGO_XBC.NEXTVAL,'CHIBS');
INSERT INTO XBC(CODIGO,NOME)
  VALUES(SEQ_CODIGO_XBC.NEXTVAL,'TIG');
  
  
SELECT SEQUENCE_NAME,INCREMENT_BY,MAX_VALUE,LAST_NUMBER FROM USER_SEQUENCES;

--EXS 6 LISTA 5 
select manager_id, min(salary) from employees
where (manager_id is not null) and (salary > 6000)
group by manager_id
order by min(salary) desc;




