SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE ADD_OUTROS(
OUTROSID OUTROS.COD_OUTRO%TYPE,
OUTROSTIPO OUTROS.TIPO%TYPE,
OUTROSEST OUTROS.ESTILO%TYPE ) 
IS

BEGIN

INSERT INTO OUTROS
VALUES(OUTROSID,OUTROSTIPO,OUTROSEST);
DBMS_OUTPUT.PUT_LINE('INSERIDO');
END;
/

EXEC ADD_OUTROS(6,'TESTE','TESTE');

SELECT * FROM OUTROS;