--Insere um Objetos_arte
CREATE OR REPLACE PROCEDURE ADD_OBJ_ART(
OBJ_ID              OBJETOS_ARTE.COD_OBJETO_ARTE%TYPE,
OBJ_ARTISTA         OBJETOS_ARTE.ARTISTA%TYPE,
OBJ_ANO             OBJETOS_ARTE.ANO%TYPE,
OBJ_TITULO          OBJETOS_ARTE.TITULO%TYPE,
OBJ_DESC            OBJETOS_ARTE.DESCRIÇÃO%TYPE,
OBJ_PAIS            OBJETOS_ARTE.PAÍS%TYPE,
OBJ_ORIGEM          OBJETOS_ARTE.ORIGEM%TYPE,
OBJ_PERIODO         OBJETOS_ARTE.PERÍODO%TYPE,
OBJ_CD_EXP          OBJETOS_ARTE.EXPOSICOES_COD_EXP%TYPE,
OBJ_CD_ARTISTA      OBJETOS_ARTE.ARTISTA_COD_ARTISTA%TYPE,
OBJ_CD_CP           OBJETOS_ARTE.COLEÇÃO_PERMANENTE_COD_CP%TYPE,
OBJ_CD_OC           OBJETOS_ARTE.OUTRAS_COLEÇÕES_COD_COLEÇÃO%TYPE,
OBJ_CD_PINTURA      OBJETOS_ARTE.PINTURA_COD_PINTURA%TYPE,
OBJ_CD_ESC          OBJETOS_ARTE.ESCULTURA_COD_ESCULTURA%TYPE,
OBJ_CD_OUTRO        OBJETOS_ARTE.OUTROS_COD_OUTRO%TYPE,
OBJ_CD_ESTATUARIA   OBJETOS_ARTE.ESTATUARIA_COD_ESTATUARIA%TYPE
) IS 
BEGIN
INSERT INTO OBJETOS_ARTE
VALUES
(
OBJ_ID,OBJ_ARTISTA,OBJ_ANO,OBJ_TITULO,OBJ_DESC,OBJ_PAIS,OBJ_ORIGEM,OBJ_PERIODO,
(SELECT COD_EXP FROM EXPOSICOES WHERE COD_EXP = OBJ_CD_EXP),
(SELECT COD_ARTISTA FROM ARTISTA WHERE COD_ARTISTA = OBJ_CD_ARTISTA),
(SELECT COD_CP FROM COLEÇÃO_PERMANENTE WHERE COD_CP = OBJ_CD_CP),
(SELECT COD_COLEÇÃO FROM OUTRAS_COLEÇÕES WHERE COD_COLEÇÃO = OBJ_CD_OC),
(SELECT COD_PINTURA FROM PINTURA WHERE COD_PINTURA = OBJ_CD_PINTURA),
(SELECT COD_ESCULTURA FROM ESCULTURA WHERE COD_ESCULTURA = OBJ_CD_ESC), 
(SELECT COD_OUTRO FROM OUTROS WHERE COD_OUTRO = OBJ_CD_OUTRO),
(SELECT COD_ESTATUARIA FROM ESTATUARIA WHERE COD_ESTATUARIA = OBJ_CD_ESTATUARIA)
);

END;
/

DESC OBJETOS_ARTE;

                              --sequencia de FK para inserção(/*cd_exp,cd_art,cd_cp,cd_coleção,cd_pi,cd_esc,cd_out,cd_esta*/)
EXEC ADD_OBJ_ART(5,'DALI',TO_DATE('12/12/1680','DD/MM/YYYY'),'QUADRO','OBRA PRIMA','ESPANHA','ESPANHA','realismo',1,2,1,null,null,1,null,null);
--null por causa do arco(controle de aplicação)



select * from objetos_arte;