--Insere em Artista
CREATE OR REPLACE PROCEDURE ADD_ARTISTA (
ARTISTAID       ARTISTA.COD_ARTISTA%TYPE,
ARTISTANOME     ARTISTA.NOME%TYPE,
AR_DATA_NASC    ARTISTA.DATA_NASC%TYPE,
AR_DATA_MOR     ARTISTA.DATA_MORTE%TYPE,
ARTISTA_PO      ARTISTA.PAÍS_DE_ORIGEM%TYPE,
AR_PERIODO      ARTISTA.PERIODO%TYPE,
AR_ESTILO       ARTISTA.ESTILO_PRINCIPAL%TYPE,
ARTISTA_DESC    ARTISTA.DESCRIÇÃO%TYPE )
IS
BEGIN

INSERT INTO ARTISTA
VALUES(ARTISTAID,ARTISTANOME,AR_DATA_NASC,AR_DATA_MOR,ARTISTA_PO,AR_PERIODO,AR_ESTILO,ARTISTA_DESC);

END;
/

EXEC ADD_ARTISTA(2,'DALI',TO_DATE('12/10/1650','DD/MM/YYYY'),TO_DATE('12/10/1850','DD/MM/YYYY'),'ESPANHA','MEDIO','REALISMO','CATALÃO');

SELECT * FROM ARTISTA;