--Insere em Cole豫o_permanente
CREATE OR REPLACE PROCEDURE ADD_CP (
CP_ID           COLE플O_PERMANENTE.COD_CP%TYPE,
CP_OBJ_ART      COLE플O_PERMANENTE.COD_OBJETO_ARTE%TYPE,
CP_DT_AQ        COLE플O_PERMANENTE.DATA_AQUISI플O%TYPE,
CP_DT_EMP       COLE플O_PERMANENTE.DATA_EMPRESTIMO%TYPE,
CP_ESTADO       COLE플O_PERMANENTE.ESTADO%TYPE,
CP_CUSTO        COLE플O_PERMANENTE.CUSTO%TYPE,
CP_DT_DV        COLE플O_PERMANENTE.DATA_DEVOLU플O%TYPE )
IS
BEGIN

INSERT INTO COLE플O_PERMANENTE
VALUES(CP_ID,(SELECT COD_OBJETO_ARTE FROM OBJETOS_ARTE
WHERE COD_OBJETO_ARTE = CP_OBJ_ART),CP_DT_AQ,CP_DT_EMP,CP_ESTADO,CP_CUSTO,CP_DT_DV);

END;
/

EXEC ADD_CP(1,1,TO_DATE('12/10/2000','DD/MM/YYYY'),TO_DATE('12/10/2001','DD/MM/YYYY'),'EM USO',5000,TO_DATE('12/10/2010','DD/MM/YYYY'));

ALTER TABLE COLE플O_PERMANENTE MODIFY CUSTO NUMBER(7,2);

INSERT INTO COLE플O_PERMANENTE
VALUES(1,1,TO_DATE('12/10/2000','DD/MM/YYYY'),TO_DATE('12/10/2001','DD/MM/YYYY'),'EM USO',5000,TO_DATE('12/10/2010','DD/MM/YYYY'));

select * from cole豫o_permanente;