--Insere em Outras_coleções
CREATE OR REPLACE PROCEDURE ADD_OC(
OC_CD_OBJ       OUTRAS_COLEÇÕES.COD_OBJETO_ARTE%TYPE,
OC_ID           OUTRAS_COLEÇÕES.COD_COLEÇÃO%TYPE,
OC_NOME         OUTRAS_COLEÇÕES.NOME%TYPE,
OC_TIPO         OUTRAS_COLEÇÕES.TIPO%TYPE,
OC_DESC         OUTRAS_COLEÇÕES.DESCRIÇÃO%TYPE,
OC_END          OUTRAS_COLEÇÕES.ENDEREÇO%TYPE,
OC_TEL          OUTRAS_COLEÇÕES.TELEFONE%TYPE
) IS

BEGIN

INSERT INTO OUTRAS_COLEÇÕES
VALUES((SELECT COD_OBJETO_ARTE FROM OBJETOS_ARTE WHERE  COD_OBJETO_ARTE = OC_CD_OBJ),OC_ID,OC_NOME,OC_TIPO,
OC_DESC,OC_END,OC_TEL);

END;
/

ALTER TABLE OUTRAS_COLEÃ‡Ã•ES MODIFY TELEFONE NUMBER(9);

EXEC ADD_OC(1,1,'PICASSO','PINTURA','TINTA OLEO','AV BRASIL',994565345);
