--Insere em Escultura
CREATE OR REPLACE PROCEDURE ADD_ESCULTURA(
ESC_ID  ESCULTURA.COD_ESCULTURA%TYPE,
ESC_MAT ESCULTURA.MATERIAL%TYPE,
ESC_ALTURA ESCULTURA.ALTURA%TYPE,
ESC_PESO ESCULTURA.PESO%TYPE,
ESC_ESTILO ESCULTURA.ESTILO%TYPE)
IS
BEGIN

INSERT INTO ESCULTURA
VALUES(ESC_ID,ESC_MAT,ESC_ALTURA,ESC_PESO,ESC_ESTILO);
END;
/

EXEC ADD_ESCULTURA(2,'CERAMICA',0.00005,0.00006,'MODERNO');
DESC ESCULTURA;

SELECT * FROM ESCULTURA;